# Generated by Django 5.2 on 2025-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('name', models.CharField(db_comment='The name of the app', help_text='The name of the app', max_length=30, primary_key=True, serialize=False)),
                ('entryPoint', models.CharField(db_comment='The entry point of the app in the webServer', help_text='The entry point of the app in the webServer', max_length=30)),
                ('displayName', models.CharField(db_comment='The name to be displayed in the menu', help_text='The name to be displayed in the menu', max_length=30)),
            ],
        ),
    ]
